### ISSUE TITLE
Searches are broken

### ISSUE THREAD

**Issue by Asthar0th** [deadprogramers/SLASH_OSINT#1]
Exception in thread Thread-2 (run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)

and moreover here

xception in thread Thread-3 (search):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sec-op/Tools/SLASH_OSINT/api/pastebin.py", line 27, in search
    cnt = db["count"]
          ~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str

**Comment by deadprogramers** [comment]
I will try to fix this issue asap

**Comment by TVikg** [comment]
Thanks very appreciated!
